version: '3.8'

services:
  umbraco:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: umbraco_container
    ports:
      - "8081:3000"
    volumes:
      - umbraco_data:/app/data
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__umbracoDbDSN=Data Source=/app/data/Umbraco.s3db;Cache=Shared
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:3000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 1m

volumes:
  umbraco_data:
